## NumPy 라이브러리 불러오기

In [1]:
import numpy as np
print(np.__version__)

1.22.4


In [2]:
import numpy
print(numpy.__version__)

1.22.4


## 리스트를 배열로 변환

In [4]:
temp = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
temp_array = np.array(temp)
print(temp)
print(temp_array)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
print(type(temp))
print(type(temp_array))
print(temp_array.shape)
print(temp_array.ndim)

<class 'list'>
<class 'numpy.ndarray'>
(10,)
1


- 참조 : https://numpy.org/doc/stable/reference/index.html#reference

- 첫번째 인수를 출력

In [7]:
temp_array[1]

2

In [8]:
temp_array[-1]

10

## 사칙연산

In [13]:
score1 = [10, 15, 24, 169, 90]
score2 = [30, 40, 70, 50, 100]

score1 + score2

[10, 15, 24, 169, 90, 30, 40, 70, 50, 100]

In [18]:
score1_arr = np.array(score1)
score2_arr = np.array(score2)
                    
result = score1_arr + score2_arr
print(np.min(result)) # 40, 55, 94, 219, 190

40


In [17]:
print(np.max(result)) # 40, 55, 94, 219, 190
print(np.sum(result)) # 40, 55, 94, 219, 190

219
598


## 배열(행렬)의 생성
- 0차원부터 3차원까지로 구성

In [19]:
temp_arr = np.array(30)
print(temp_arr)
print(type(temp_arr))
print(temp_arr.shape)

30
<class 'numpy.ndarray'>
()


In [22]:
temp_arr = np.array([1, 2, 3])
print(temp_arr.shape)
print(temp_arr.ndim)

(3,)
1


## 2차원
- 정형 데이터(엑셀 데이터)

In [23]:
temp_arr = np.array([[1,2,3], [4,5,6]])
print(temp_arr.shape)
print(temp_arr.ndim)

(2, 3)
2


## 3차원
- 이미지 데이터

In [ ]:
temp_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(temp_arr.shape)
print(temp_arr.ndim)

In [28]:
temp_arr = np.array([1, 2, 3, 4], ndmin=3)
print(temp_arr.shape)
print(temp_arr.ndim)

(1, 1, 4)
3


## 배열 생성의 다양한 방법들
- 모두 0으로 채운다다

In [35]:
temp_arr = np.zeros((3, 2))
temp_arr.dtype #.dtpye : data type

float64


In [32]:
temp_arr = np.ones((5, 10))
temp_arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

- 임의의 상수값으로 채운다다

In [36]:
temp_arr = np.full((2, 3), 10)
temp_arr

array([[10, 10, 10],
       [10, 10, 10]])

- 최소 및 최대 숫자의 범위를 정해두고, 구간별로 값을 생성하는 코드를 작성함

In [37]:
temp_arr = np.linspace(5, 10, 5)
temp_arr

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

- np.arange()

In [42]:
temp_arr = np.arange(1, 10, 2)
temp_arr

array([1, 3, 5, 7, 9])

- 임의의 난수 생성

In [49]:
from numpy.random import rand
x = rand()
print(x)

0.8178746617331211


In [47]:
from numpy import random
x = random.rand()
print(x)

0.4759617723881314


In [48]:
import numpy as np
x = np.random.rand()
print(x)

0.7269296328722762


## 배열 연산
- 덧셈 : np.add()
- 뺄셈 : np.subtract()
- 곱셈 : np.multiply()
- 나눗셈 : np.divide()

In [50]:
import numpy as np

array_01 = np.array([1, 2, 3])
array_02 = np.array([10, 20, 30])

# 덧셈
result = np.add(array_01, array_02)
result

array([11, 22, 33])

In [51]:
# 뺄셈
result = np.subtract(array_01, array_02)
result

array([ -9, -18, -27])

In [52]:
# 곱셈
result = np.multiply(array_01, array_02)
result

array([10, 40, 90])

In [53]:
# 나눗셈
result = np.divide(array_01, array_02)
result

array([0.1, 0.1, 0.1])

In [54]:
array_01 = np.array([1, 2, 3])
array_02 = np.array([1, 2, 3])

result = np.power(array_01, array_02)
print(result)

[ 1  4 27]


## 소숫점 정렬
- 소수점 절삭삭

- 코드는 실행속도를 체크해야 한다.

In [61]:
%%time

temp_arr = np.trunc([-1.23, 1.23])
print(temp_arr)

[-1.  1.]
CPU times: user 1.55 ms, sys: 0 ns, total: 1.55 ms
Wall time: 5.3 ms


In [60]:
%%time

temp_arr = np.fix([-1.23, 1.23])
print(temp_arr)

[-1.  1.]
CPU times: user 2.23 ms, sys: 0 ns, total: 2.23 ms
Wall time: 2.17 ms


- 소숫점 자리에서 반올림

In [58]:
temp_arr = np.around([-1.123131, 1.123131], 3)
temp_arr

array([-1.123,  1.123])

In [59]:
temp_arr = np.round([-1.123131, 1.123131], 3)
temp_arr

array([-1.123,  1.123])

- 소숫점 모두

In [66]:
import time

# Start time
start_time = time.time()

temp_arr = np.floor([-1.23456, 1.23456])
print(temp_arr)

# End time
end_time = time.time()

# Execution time
execution_time = end_time - start_time

print("Execution time:", execution_time)

[-2.  1.]
Execution time: 0.0011754035949707031


In [65]:
import time

# Start time
start_time = time.time()

temp_arr = np.ceil([-1.23456, 1.23456])
print(temp_arr)

# End time
end_time = time.time()

# Execution time
execution_time = end_time - start_time

print("Execution time:", execution_time)

[-1.  2.]
Execution time: 0.0007002353668212891


## 조건문
- where : 조건식 1개일 때 활용
- select : 다중조건일 때 활용

In [67]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- np.where

In [68]:
np.where(temp_arr < 5, temp_arr, 10 * temp_arr)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

- np.select

In [72]:
temp_arr = np.arange(10)
cond_list = [temp_arr > 5, temp_arr < 2]
choice_list = [temp_arr * 3, temp_arr + 10]

np.select(cond_list, choice_list, default=temp_arr)

array([10, 11,  2,  3,  4,  5, 18, 21, 24, 27])